[general]
live_config_reload = true
import = ["~/.dotfiles/terminal/alacritty/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
chars = '''
printf "\033c"
'''
key = "K"
mods = "Control|Shift"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9
