live_config_reload = true

[colors.bright]
black = "0x6d6d6d"
blue = "0x5a8af9"
cyan = "0x71ecff"
green = "0x94f8a9"
magenta = "0x9088cb"
red = "0xff6e67"
white = "0xf8f1ff"
yellow = "0xfffc67"

[colors.normal]
black = "0x000000"
blue = "0x3e58df"
cyan = "0x6ce1f3"
green = "0x8deca1"
magenta = "0xb3a8fc"
red = "0xff80ab"
white = "0xc7c7c7"
yellow = "0xfeec6e"

[colors.primary]
background = "0x000000"
foreground = "0xc7c7c7"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
chars = '''
printf "\033c"
'''
key = "K"
mods = "Control|Shift"

[window]
decorations = "Full"
dynamic_title = true
opacity = 0.9
